/*2024-03-13T15:02:31-01:00*/

/********************************************************************
 * dcmotor_1.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__DCMOTOR_1_H
#define _MY_APP__DCMOTOR_1_H


/********************** Variable declarations ***********************/

extern CB_Index dcmotor_1__num;
extern CB_Mem_Float *dcmotor_1_wB;
extern CB_Mem_Float *dcmotor_1_I;
extern CB_Mem_Float *dcmotor_1_U;
extern CB_Mem_Float *dcmotor_1_M_mot;

/********************** Function declarations ***********************/

extern int _my_app__dcmotor_1_init(void);
extern int my_app__dcmotor_1(void);

#endif /*_MY_APP__DCMOTOR_1_H*/
