/*2024-03-18T16:40:19-01:00*/

/********************************************************************
 * batch.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__BATCH_H
#define _MY_APP__BATCH_H


/********************** Variable declarations ***********************/

extern CB_Index batch__num;

/********************** Function declarations ***********************/

extern int _my_app__batch_init(void);
extern int my_app__batch(void);

#endif /*_MY_APP__BATCH_H*/
