/*2024-03-13T11:33:32-01:00*/

/********************************************************************
 * dcmotor.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__DCMOTOR_H
#define _MY_APP__DCMOTOR_H


/********************** Variable declarations ***********************/

extern CB_Index dcmotor__num;
extern CB_Mem_Float *dcmotor_wB;
extern CB_Mem_Float *dcmotor_I;
extern CB_Mem_Float *dcmotor_U;
extern CB_Mem_Float *dcmotor_M_mot;

/********************** Function declarations ***********************/

extern int _my_app__dcmotor_init(void);
extern int my_app__dcmotor(void);

#endif /*_MY_APP__DCMOTOR_H*/
