/*2024-03-14T09:59:36-01:00*/

/********************************************************************
 * rien2.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"


/********************************************************************
 *                    Inner 'aaa1' declarations                     *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index aaa1__num;

/********************** Function declarations ***********************/

static int _my_app__aaa1_init(void);
static int my_app__aaa1(void);

/********************************************************************
 *                     Inner 'st1' declarations                     *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index st1__num;

/********************** Function declarations ***********************/

static int _my_app__st1_init(void);
static int my_app__st1(void);

/********************************************************************
 *                   Inner 'aaa1' implementation                    *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index aaa1__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__aaa1_offset_st1;
static CB_Offset my_app__aaa1_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__aaa1_init(void)
{
	CB_Object __start = self;

	/*initialize child st1 (my_app.st1):*/
	self_num++;
	my_app__aaa1_offset_st1.Bool = self.Bool - __start.Bool;
	my_app__aaa1_offset_st1.Int = self.Int - __start.Int;
	my_app__aaa1_offset_st1.Float = self.Float - __start.Float;
	my_app__aaa1_offset_st1.Char = self.Char - __start.Char;
	_my_app__st1_init();

	my_app__aaa1_offset__end.Bool = self.Bool - __start.Bool;
	my_app__aaa1_offset__end.Int = self.Int - __start.Int;
	my_app__aaa1_offset__end.Float = self.Float - __start.Float;
	my_app__aaa1_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__aaa1(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__aaa1_offset_st1.Bool;
			self.Int = __start.Int + my_app__aaa1_offset_st1.Int;
			self.Float = __start.Float + my_app__aaa1_offset_st1.Float;
			self.Char = __start.Char + my_app__aaa1_offset_st1.Char;

			/************************** st1 execution ***************************/

			self_num++;
			if (st1__num != self_num) {
				st1__num = self_num;
			}
			__ret = my_app__st1();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__aaa1_offset__end.Bool;
	self.Int = __start.Int + my_app__aaa1_offset__end.Int;
	self.Float = __start.Float + my_app__aaa1_offset__end.Float;
	self.Char = __start.Char + my_app__aaa1_offset__end.Char;

	return 0;
}


/********************************************************************
 *                    Inner 'st1' implementation                    *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index st1__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__st1_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__st1(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}


/********************************************************************
 *               Public 'my_app.rien2' implementation               *
 ********************************************************************/

#include "rien2.h"


/**************************** Variables *****************************/

CB_Index rien2__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__rien2_offset_aaa1;
static CB_Offset my_app__rien2_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _my_app__rien2_init(void)
{
	CB_Object __start = self;

	/*initialize child aaa1 (my_app.aaa1):*/
	self_num++;
	my_app__rien2_offset_aaa1.Bool = self.Bool - __start.Bool;
	my_app__rien2_offset_aaa1.Int = self.Int - __start.Int;
	my_app__rien2_offset_aaa1.Float = self.Float - __start.Float;
	my_app__rien2_offset_aaa1.Char = self.Char - __start.Char;
	_my_app__aaa1_init();

	my_app__rien2_offset__end.Bool = self.Bool - __start.Bool;
	my_app__rien2_offset__end.Int = self.Int - __start.Int;
	my_app__rien2_offset__end.Float = self.Float - __start.Float;
	my_app__rien2_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int my_app__rien2(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__rien2_offset_aaa1.Bool;
			self.Int = __start.Int + my_app__rien2_offset_aaa1.Int;
			self.Float = __start.Float + my_app__rien2_offset_aaa1.Float;
			self.Char = __start.Char + my_app__rien2_offset_aaa1.Char;

			/************************** aaa1 execution **************************/

			self_num++;
			if (aaa1__num != self_num) {
				aaa1__num = self_num;
			}
			__ret = my_app__aaa1();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__rien2_offset__end.Bool;
	self.Int = __start.Int + my_app__rien2_offset__end.Int;
	self.Float = __start.Float + my_app__rien2_offset__end.Float;
	self.Char = __start.Char + my_app__rien2_offset__end.Char;

	return 0;
}

