/*2024-03-14T09:59:36-01:00*/

/********************************************************************
 * rien2.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__RIEN2_H
#define _MY_APP__RIEN2_H


/********************** Variable declarations ***********************/

extern CB_Index rien2__num;

/********************** Function declarations ***********************/

extern int _my_app__rien2_init(void);
extern int my_app__rien2(void);

#endif /*_MY_APP__RIEN2_H*/
