/*2024-03-18T18:11:39-01:00*/

/********************************************************************
 * tni_clock_4.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__TNI_CLOCK_4_H
#define _MY_APP__TNI_CLOCK_4_H


/********************** Variable declarations ***********************/

extern CB_Index tni_clock_4__num;
extern CB_Mem_Int *tni_clock_4_depth;
extern CB_Mem_Bool *tni_clock_4_B1;
extern CB_Mem_Bool *tni_clock_4_B2;
extern CB_Mem_Bool *tni_clock_4_B3;
extern CB_Mem_Bool *tni_clock_4_B4;

/********************** Function declarations ***********************/

extern int _my_app__tni_clock_4_init(void);
extern int my_app__tni_clock_4(void);

#endif /*_MY_APP__TNI_CLOCK_4_H*/
