/*2024-03-18T18:02:14-01:00*/

/********************************************************************
 * tni_clock_3.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"


/********************************************************************
 *                 Inner 'environment' declarations                 *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index environment__num;
extern CB_Mem_Int *_i_tni_clock_3__environment_depth;
extern CB_Mem_Bool *_i_tni_clock_3__environment_B1;
extern CB_Mem_Bool *_i_tni_clock_3__environment_B2;
extern CB_Mem_Bool *_i_tni_clock_3__environment_B3;
extern CB_Mem_Bool *_i_tni_clock_3__environment_B4;
extern CB_Mem_Float *_i_tni_clock_3__environment_hydrostaticPressure;
extern CB_Mem_Float *_i_tni_clock_3__environment_absolutePressure;
extern CB_Mem_Int *_i_tni_clock_3__environment_pressure;
extern CB_Mem_Bool *_i_tni_clock_3__environment_tick;

/********************** Function declarations ***********************/

static int _my_app__environment_init(void);
static int my_app__environment(void);

/********************************************************************
 *                 Inner 'controller' declarations                  *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index controller__num;
extern CB_Mem_Int *_i_tni_clock_3__controller_pressure;
extern CB_Mem_Bool *_i_tni_clock_3__controller_tick;
extern CB_Mem_Bool *_i_tni_clock_3__controller_B1;
extern CB_Mem_Bool *_i_tni_clock_3__controller_B2;
extern CB_Mem_Bool *_i_tni_clock_3__controller_B3;
extern CB_Mem_Bool *_i_tni_clock_3__controller_B4;
extern CB_Mem_Bool *_i_tni_clock_3__controller_displayValue;
extern CB_Mem_Bool *_i_tni_clock_3__controller_stepMotorSecond;
extern CB_Mem_Bool *_i_tni_clock_3__controller_stepMotorMinute;
extern CB_Mem_Bool *_i_tni_clock_3__controller_stepMotorHour;
extern CB_Mem_Bool *_i_tni_clock_3__controller_switchOnLight;

/********************** Function declarations ***********************/

static int _my_app__controller_init(void);
static int my_app__controller(void);

/********************************************************************
 *               Inner 'timemanagement' declarations                *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index timemanagement__num;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_tick;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_B1;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_B2;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_B3;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_B4;
extern CB_Mem_Float *_i_tni_clock_3__timemanagement_tickCount;
extern CB_Mem_Int *_i_tni_clock_3__timemanagement_adjustMode;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_stepMotorSecond;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_stepMotorMinute;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_stepMotorHour;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_hh;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_mn;
extern CB_Mem_Bool *_i_tni_clock_3__timemanagement_sec;

/********************** Function declarations ***********************/

static int _my_app__timemanagement_init(void);
static int my_app__timemanagement(void);

/********************************************************************
 *              Inner 'displaymanagement' declarations              *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index displaymanagement__num;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_hh;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_mn;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_sec;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_tick;
extern CB_Mem_Int *_i_tni_clock_3__displaymanagement_pressure;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B1;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B2;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B3;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B4;
extern CB_Mem_Float *_i_tni_clock_3__displaymanagement_displayTime;
extern CB_Mem_Float *_i_tni_clock_3__displaymanagement_lampSwitchOnTime;
extern CB_Mem_Int *_i_tni_clock_3__displaymanagement_pulseTime;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_displayValue;
extern CB_Mem_Bool *_i_tni_clock_3__displaymanagement_switchOnLight;

/********************** Function declarations ***********************/

static int _my_app__displaymanagement_init(void);
static int my_app__displaymanagement(void);

/********************************************************************
 *                     Inner 'lcd' declarations                     *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index lcd__num;
extern CB_Mem_Bool *_i_tni_clock_3__lcd_displayValue;
extern CB_Mem_Bool *_i_tni_clock_3__lcd_displayString;
extern CB_Mem_Bool *_i_tni_clock_3__lcd_i;

/********************** Function declarations ***********************/

static int _my_app__lcd_init(void);
static int my_app__lcd(void);

/********************************************************************
 *                   Inner 'motors' declarations                    *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index motors__num;
extern CB_Mem_Bool *_i_tni_clock_3__motors_stepMotorSecond;
extern CB_Mem_Bool *_i_tni_clock_3__motors_stepMotorMinute;
extern CB_Mem_Bool *_i_tni_clock_3__motors_stepMotorHour;
extern CB_Mem_Int *_i_tni_clock_3__motors_hourHand;
extern CB_Mem_Int *_i_tni_clock_3__motors_minuteHand;
extern CB_Mem_Int *_i_tni_clock_3__motors_secondHand;

/********************** Function declarations ***********************/

static int _my_app__motors_init(void);
static int my_app__motors(void);

/********************************************************************
 *                    Inner 'light' declarations                    *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index light__num;
extern CB_Mem_Bool *_i_tni_clock_3__light_switchOnLight;

/********************** Function declarations ***********************/

static int _my_app__light_init(void);
static int my_app__light(void);

/********************************************************************
 *                Inner 'environment' implementation                *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index environment__num = 0;
CB_Mem_Int *_i_tni_clock_3__environment_depth;
CB_Mem_Bool *_i_tni_clock_3__environment_B1;
CB_Mem_Bool *_i_tni_clock_3__environment_B2;
CB_Mem_Bool *_i_tni_clock_3__environment_B3;
CB_Mem_Bool *_i_tni_clock_3__environment_B4;
CB_Mem_Float *_i_tni_clock_3__environment_hydrostaticPressure;
CB_Mem_Float *_i_tni_clock_3__environment_absolutePressure;
CB_Mem_Int *_i_tni_clock_3__environment_pressure;
CB_Mem_Bool *_i_tni_clock_3__environment_tick;

/**************************** Variables *****************************/

#define depth (*((short *)&(_i_tni_clock_3__environment_depth->CB_current_value) + ALIGN_OFFSET_SHORT))
#define B1 (_i_tni_clock_3__environment_B1->CB_current_value)
#define B2 (_i_tni_clock_3__environment_B2->CB_current_value)
#define B3 (_i_tni_clock_3__environment_B3->CB_current_value)
#define B4 (_i_tni_clock_3__environment_B4->CB_current_value)
#define hydrostaticPressure (_i_tni_clock_3__environment_hydrostaticPressure->CB_current_value)
#define absolutePressure (_i_tni_clock_3__environment_absolutePressure->CB_current_value)
#define pressure (*((short *)&(_i_tni_clock_3__environment_pressure->CB_current_value) + ALIGN_OFFSET_SHORT))
#define tick (_i_tni_clock_3__environment_tick->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__environment_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__environment(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_int(_i_tni_clock_3__environment_pressure);
		CB_post_bool(_i_tni_clock_3__environment_tick);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef depth
#undef B1
#undef B2
#undef B3
#undef B4
#undef hydrostaticPressure
#undef absolutePressure
#undef pressure
#undef tick

/********************************************************************
 *                Inner 'controller' implementation                 *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index controller__num = 0;
CB_Mem_Int *_i_tni_clock_3__controller_pressure;
CB_Mem_Bool *_i_tni_clock_3__controller_tick;
CB_Mem_Bool *_i_tni_clock_3__controller_B1;
CB_Mem_Bool *_i_tni_clock_3__controller_B2;
CB_Mem_Bool *_i_tni_clock_3__controller_B3;
CB_Mem_Bool *_i_tni_clock_3__controller_B4;
CB_Mem_Bool *_i_tni_clock_3__controller_displayValue;
CB_Mem_Bool *_i_tni_clock_3__controller_stepMotorSecond;
CB_Mem_Bool *_i_tni_clock_3__controller_stepMotorMinute;
CB_Mem_Bool *_i_tni_clock_3__controller_stepMotorHour;
CB_Mem_Bool *_i_tni_clock_3__controller_switchOnLight;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__controller_offset_timeManagement;
static CB_Offset my_app__controller_offset_displayManagement;
static CB_Offset my_app__controller_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__controller_init(void)
{
	CB_Object __start = self;
	self.Bool+=3;
	self.Int+=2;
	self.Float+=3;

	/*initialize child timeManagement (my_app.timemanagement):*/
	self_num++;
	my_app__controller_offset_timeManagement.Bool = self.Bool - __start.Bool;
	my_app__controller_offset_timeManagement.Int = self.Int - __start.Int;
	my_app__controller_offset_timeManagement.Float = self.Float - __start.Float;
	my_app__controller_offset_timeManagement.Char = self.Char - __start.Char;
	_i_tni_clock_3__timemanagement_tick = _i_tni_clock_3__controller_tick;
	_i_tni_clock_3__timemanagement_B1 = _i_tni_clock_3__controller_B1;
	_i_tni_clock_3__timemanagement_B2 = _i_tni_clock_3__controller_B2;
	_i_tni_clock_3__timemanagement_B3 = _i_tni_clock_3__controller_B3;
	_i_tni_clock_3__timemanagement_B4 = _i_tni_clock_3__controller_B4;
	_i_tni_clock_3__timemanagement_tickCount = __start.Float+2; /*controller__cn_4*/
	_i_tni_clock_3__timemanagement_adjustMode = __start.Int+1; /*controller__cn_5*/
	_i_tni_clock_3__timemanagement_stepMotorSecond = _i_tni_clock_3__controller_stepMotorSecond;
	_i_tni_clock_3__timemanagement_stepMotorMinute = _i_tni_clock_3__controller_stepMotorMinute;
	_i_tni_clock_3__timemanagement_stepMotorHour = _i_tni_clock_3__controller_stepMotorHour;
	_i_tni_clock_3__timemanagement_hh = __start.Bool+0; /*controller__cn_3*/
	_i_tni_clock_3__timemanagement_mn = __start.Bool+1; /*controller__cn_2*/
	_i_tni_clock_3__timemanagement_sec = __start.Bool+2; /*controller__cn_1*/
	_my_app__timemanagement_init();

	/*initialize child displayManagement (my_app.displaymanagement):*/
	self_num++;
	my_app__controller_offset_displayManagement.Bool = self.Bool - __start.Bool;
	my_app__controller_offset_displayManagement.Int = self.Int - __start.Int;
	my_app__controller_offset_displayManagement.Float = self.Float - __start.Float;
	my_app__controller_offset_displayManagement.Char = self.Char - __start.Char;
	_i_tni_clock_3__displaymanagement_hh = __start.Bool+0; /*controller__cn_3*/
	_i_tni_clock_3__displaymanagement_mn = __start.Bool+1; /*controller__cn_2*/
	_i_tni_clock_3__displaymanagement_sec = __start.Bool+2; /*controller__cn_1*/
	_i_tni_clock_3__displaymanagement_tick = _i_tni_clock_3__controller_tick;
	_i_tni_clock_3__displaymanagement_pressure = _i_tni_clock_3__controller_pressure;
	_i_tni_clock_3__displaymanagement_B1 = _i_tni_clock_3__controller_B1;
	_i_tni_clock_3__displaymanagement_B2 = _i_tni_clock_3__controller_B2;
	_i_tni_clock_3__displaymanagement_B3 = _i_tni_clock_3__controller_B3;
	_i_tni_clock_3__displaymanagement_B4 = _i_tni_clock_3__controller_B4;
	_i_tni_clock_3__displaymanagement_displayTime = __start.Float+1; /*controller__cn_6*/
	_i_tni_clock_3__displaymanagement_lampSwitchOnTime = __start.Float+0; /*controller__cn_7*/
	_i_tni_clock_3__displaymanagement_pulseTime = __start.Int+0; /*controller__cn_8*/
	_i_tni_clock_3__displaymanagement_displayValue = _i_tni_clock_3__controller_displayValue;
	_i_tni_clock_3__displaymanagement_switchOnLight = _i_tni_clock_3__controller_switchOnLight;
	_my_app__displaymanagement_init();

	my_app__controller_offset__end.Bool = self.Bool - __start.Bool;
	my_app__controller_offset__end.Int = self.Int - __start.Int;
	my_app__controller_offset__end.Float = self.Float - __start.Float;
	my_app__controller_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__controller(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__controller_offset_timeManagement.Bool;
			self.Int = __start.Int + my_app__controller_offset_timeManagement.Int;
			self.Float = __start.Float + my_app__controller_offset_timeManagement.Float;
			self.Char = __start.Char + my_app__controller_offset_timeManagement.Char;

			/********************* timeManagement execution *********************/

			self_num++;
			if (timemanagement__num != self_num) {
				timemanagement__num = self_num;
				_i_tni_clock_3__timemanagement_tick = _i_tni_clock_3__controller_tick;
				_i_tni_clock_3__timemanagement_B1 = _i_tni_clock_3__controller_B1;
				_i_tni_clock_3__timemanagement_B2 = _i_tni_clock_3__controller_B2;
				_i_tni_clock_3__timemanagement_B3 = _i_tni_clock_3__controller_B3;
				_i_tni_clock_3__timemanagement_B4 = _i_tni_clock_3__controller_B4;
				_i_tni_clock_3__timemanagement_tickCount = __start.Float+2; /*controller__cn_4*/
				_i_tni_clock_3__timemanagement_adjustMode = __start.Int+1; /*controller__cn_5*/
				_i_tni_clock_3__timemanagement_stepMotorSecond = _i_tni_clock_3__controller_stepMotorSecond;
				_i_tni_clock_3__timemanagement_stepMotorMinute = _i_tni_clock_3__controller_stepMotorMinute;
				_i_tni_clock_3__timemanagement_stepMotorHour = _i_tni_clock_3__controller_stepMotorHour;
				_i_tni_clock_3__timemanagement_hh = __start.Bool+0; /*controller__cn_3*/
				_i_tni_clock_3__timemanagement_mn = __start.Bool+1; /*controller__cn_2*/
				_i_tni_clock_3__timemanagement_sec = __start.Bool+2; /*controller__cn_1*/
			}
			__ret = my_app__timemanagement();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************* displayManagement execution ********************/

			self_num++;
			if (displaymanagement__num != self_num) {
				displaymanagement__num = self_num;
				_i_tni_clock_3__displaymanagement_hh = __start.Bool+0; /*controller__cn_3*/
				_i_tni_clock_3__displaymanagement_mn = __start.Bool+1; /*controller__cn_2*/
				_i_tni_clock_3__displaymanagement_sec = __start.Bool+2; /*controller__cn_1*/
				_i_tni_clock_3__displaymanagement_tick = _i_tni_clock_3__controller_tick;
				_i_tni_clock_3__displaymanagement_pressure = _i_tni_clock_3__controller_pressure;
				_i_tni_clock_3__displaymanagement_B1 = _i_tni_clock_3__controller_B1;
				_i_tni_clock_3__displaymanagement_B2 = _i_tni_clock_3__controller_B2;
				_i_tni_clock_3__displaymanagement_B3 = _i_tni_clock_3__controller_B3;
				_i_tni_clock_3__displaymanagement_B4 = _i_tni_clock_3__controller_B4;
				_i_tni_clock_3__displaymanagement_displayTime = __start.Float+1; /*controller__cn_6*/
				_i_tni_clock_3__displaymanagement_lampSwitchOnTime = __start.Float+0; /*controller__cn_7*/
				_i_tni_clock_3__displaymanagement_pulseTime = __start.Int+0; /*controller__cn_8*/
				_i_tni_clock_3__displaymanagement_displayValue = _i_tni_clock_3__controller_displayValue;
				_i_tni_clock_3__displaymanagement_switchOnLight = _i_tni_clock_3__controller_switchOnLight;
			}
			__ret = my_app__displaymanagement();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__controller_offset__end.Bool;
	self.Int = __start.Int + my_app__controller_offset__end.Int;
	self.Float = __start.Float + my_app__controller_offset__end.Float;
	self.Char = __start.Char + my_app__controller_offset__end.Char;

	return 0;
}


/********************************************************************
 *              Inner 'timemanagement' implementation               *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index timemanagement__num = 0;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_tick;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_B1;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_B2;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_B3;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_B4;
CB_Mem_Float *_i_tni_clock_3__timemanagement_tickCount;
CB_Mem_Int *_i_tni_clock_3__timemanagement_adjustMode;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_stepMotorSecond;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_stepMotorMinute;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_stepMotorHour;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_hh;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_mn;
CB_Mem_Bool *_i_tni_clock_3__timemanagement_sec;

/**************************** Variables *****************************/

#define tick (_i_tni_clock_3__timemanagement_tick->CB_current_value)
#define B1 (_i_tni_clock_3__timemanagement_B1->CB_current_value)
#define B2 (_i_tni_clock_3__timemanagement_B2->CB_current_value)
#define B3 (_i_tni_clock_3__timemanagement_B3->CB_current_value)
#define B4 (_i_tni_clock_3__timemanagement_B4->CB_current_value)
#define tickCount (_i_tni_clock_3__timemanagement_tickCount->CB_current_value)
#define adjustMode (*((short *)&(_i_tni_clock_3__timemanagement_adjustMode->CB_current_value) + ALIGN_OFFSET_SHORT))
#define stepMotorSecond (_i_tni_clock_3__timemanagement_stepMotorSecond->CB_current_value)
#define stepMotorMinute (_i_tni_clock_3__timemanagement_stepMotorMinute->CB_current_value)
#define stepMotorHour (_i_tni_clock_3__timemanagement_stepMotorHour->CB_current_value)
#define hh (_i_tni_clock_3__timemanagement_hh->CB_current_value)
#define mn (_i_tni_clock_3__timemanagement_mn->CB_current_value)
#define sec (_i_tni_clock_3__timemanagement_sec->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__timemanagement_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__timemanagement(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_bool(_i_tni_clock_3__timemanagement_stepMotorSecond);
		CB_post_bool(_i_tni_clock_3__timemanagement_stepMotorMinute);
		CB_post_bool(_i_tni_clock_3__timemanagement_stepMotorHour);
		CB_post_bool(_i_tni_clock_3__timemanagement_hh);
		CB_post_bool(_i_tni_clock_3__timemanagement_mn);
		CB_post_bool(_i_tni_clock_3__timemanagement_sec);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef tick
#undef B1
#undef B2
#undef B3
#undef B4
#undef tickCount
#undef adjustMode
#undef stepMotorSecond
#undef stepMotorMinute
#undef stepMotorHour
#undef hh
#undef mn
#undef sec

/********************************************************************
 *             Inner 'displaymanagement' implementation             *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index displaymanagement__num = 0;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_hh;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_mn;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_sec;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_tick;
CB_Mem_Int *_i_tni_clock_3__displaymanagement_pressure;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B1;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B2;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B3;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_B4;
CB_Mem_Float *_i_tni_clock_3__displaymanagement_displayTime;
CB_Mem_Float *_i_tni_clock_3__displaymanagement_lampSwitchOnTime;
CB_Mem_Int *_i_tni_clock_3__displaymanagement_pulseTime;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_displayValue;
CB_Mem_Bool *_i_tni_clock_3__displaymanagement_switchOnLight;

/**************************** Variables *****************************/

#define hh (_i_tni_clock_3__displaymanagement_hh->CB_current_value)
#define mn (_i_tni_clock_3__displaymanagement_mn->CB_current_value)
#define sec (_i_tni_clock_3__displaymanagement_sec->CB_current_value)
#define tick (_i_tni_clock_3__displaymanagement_tick->CB_current_value)
#define pressure (*((short *)&(_i_tni_clock_3__displaymanagement_pressure->CB_current_value) + ALIGN_OFFSET_SHORT))
#define B1 (_i_tni_clock_3__displaymanagement_B1->CB_current_value)
#define B2 (_i_tni_clock_3__displaymanagement_B2->CB_current_value)
#define B3 (_i_tni_clock_3__displaymanagement_B3->CB_current_value)
#define B4 (_i_tni_clock_3__displaymanagement_B4->CB_current_value)
#define displayTime (_i_tni_clock_3__displaymanagement_displayTime->CB_current_value)
#define lampSwitchOnTime (_i_tni_clock_3__displaymanagement_lampSwitchOnTime->CB_current_value)
#define pulseTime (*((short *)&(_i_tni_clock_3__displaymanagement_pulseTime->CB_current_value) + ALIGN_OFFSET_SHORT))
#define displayValue (_i_tni_clock_3__displaymanagement_displayValue->CB_current_value)
#define switchOnLight (_i_tni_clock_3__displaymanagement_switchOnLight->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__displaymanagement_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__displaymanagement(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_bool(_i_tni_clock_3__displaymanagement_displayValue);
		CB_post_bool(_i_tni_clock_3__displaymanagement_switchOnLight);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef hh
#undef mn
#undef sec
#undef tick
#undef pressure
#undef B1
#undef B2
#undef B3
#undef B4
#undef displayTime
#undef lampSwitchOnTime
#undef pulseTime
#undef displayValue
#undef switchOnLight

/********************************************************************
 *                    Inner 'lcd' implementation                    *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index lcd__num = 0;
CB_Mem_Bool *_i_tni_clock_3__lcd_displayValue;
CB_Mem_Bool *_i_tni_clock_3__lcd_displayString;
CB_Mem_Bool *_i_tni_clock_3__lcd_i;

/**************************** Variables *****************************/

#define displayValue (_i_tni_clock_3__lcd_displayValue->CB_current_value)
#define displayString (_i_tni_clock_3__lcd_displayString->CB_current_value)
#define i (_i_tni_clock_3__lcd_i->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__lcd_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__lcd(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef displayValue
#undef displayString
#undef i

/********************************************************************
 *                  Inner 'motors' implementation                   *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index motors__num = 0;
CB_Mem_Bool *_i_tni_clock_3__motors_stepMotorSecond;
CB_Mem_Bool *_i_tni_clock_3__motors_stepMotorMinute;
CB_Mem_Bool *_i_tni_clock_3__motors_stepMotorHour;
CB_Mem_Int *_i_tni_clock_3__motors_hourHand;
CB_Mem_Int *_i_tni_clock_3__motors_minuteHand;
CB_Mem_Int *_i_tni_clock_3__motors_secondHand;

/**************************** Variables *****************************/

#define stepMotorSecond (_i_tni_clock_3__motors_stepMotorSecond->CB_current_value)
#define stepMotorMinute (_i_tni_clock_3__motors_stepMotorMinute->CB_current_value)
#define stepMotorHour (_i_tni_clock_3__motors_stepMotorHour->CB_current_value)
#define hourHand (*((short *)&(_i_tni_clock_3__motors_hourHand->CB_current_value) + ALIGN_OFFSET_SHORT))
#define minuteHand (*((short *)&(_i_tni_clock_3__motors_minuteHand->CB_current_value) + ALIGN_OFFSET_SHORT))
#define secondHand (*((short *)&(_i_tni_clock_3__motors_secondHand->CB_current_value) + ALIGN_OFFSET_SHORT))


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__motors_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__motors(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef stepMotorSecond
#undef stepMotorMinute
#undef stepMotorHour
#undef hourHand
#undef minuteHand
#undef secondHand

/********************************************************************
 *                   Inner 'light' implementation                   *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index light__num = 0;
CB_Mem_Bool *_i_tni_clock_3__light_switchOnLight;

/**************************** Variables *****************************/

#define switchOnLight (_i_tni_clock_3__light_switchOnLight->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__light_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__light(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef switchOnLight

/********************************************************************
 *            Public 'my_app.tni_clock_3' implementation            *
 ********************************************************************/

#include "tni_clock_3.h"


/**************************** Variables *****************************/

CB_Index tni_clock_3__num = 0;
CB_Mem_Int *tni_clock_3_depth;
CB_Mem_Bool *tni_clock_3_B1;
CB_Mem_Bool *tni_clock_3_B2;
CB_Mem_Bool *tni_clock_3_B3;
CB_Mem_Bool *tni_clock_3_B4;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__tni_clock_3_offset_environment;
static CB_Offset my_app__tni_clock_3_offset_controller;
static CB_Offset my_app__tni_clock_3_offset_LCD;
static CB_Offset my_app__tni_clock_3_offset_motors;
static CB_Offset my_app__tni_clock_3_offset_light;
static CB_Offset my_app__tni_clock_3_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _my_app__tni_clock_3_init(void)
{
	CB_Object __start = self;
	self.Bool+=8;
	self.Int+=4;
	self.Float+=2;

	/*initialize child environment (my_app.environment):*/
	self_num++;
	my_app__tni_clock_3_offset_environment.Bool = self.Bool - __start.Bool;
	my_app__tni_clock_3_offset_environment.Int = self.Int - __start.Int;
	my_app__tni_clock_3_offset_environment.Float = self.Float - __start.Float;
	my_app__tni_clock_3_offset_environment.Char = self.Char - __start.Char;
	_i_tni_clock_3__environment_depth = tni_clock_3_depth;
	_i_tni_clock_3__environment_B1 = tni_clock_3_B1;
	_i_tni_clock_3__environment_B2 = tni_clock_3_B2;
	_i_tni_clock_3__environment_B3 = tni_clock_3_B3;
	_i_tni_clock_3__environment_B4 = tni_clock_3_B4;
	_i_tni_clock_3__environment_hydrostaticPressure = __start.Float+1; /*tni_clock_3__cn_8*/
	_i_tni_clock_3__environment_absolutePressure = __start.Float+0; /*tni_clock_3__cn_9*/
	_i_tni_clock_3__environment_pressure = __start.Int+3; /*tni_clock_3__cn_7*/
	_i_tni_clock_3__environment_tick = __start.Bool+2; /*tni_clock_3__cn_6*/
	_my_app__environment_init();

	/*initialize child controller (my_app.controller):*/
	self_num++;
	my_app__tni_clock_3_offset_controller.Bool = self.Bool - __start.Bool;
	my_app__tni_clock_3_offset_controller.Int = self.Int - __start.Int;
	my_app__tni_clock_3_offset_controller.Float = self.Float - __start.Float;
	my_app__tni_clock_3_offset_controller.Char = self.Char - __start.Char;
	_i_tni_clock_3__controller_pressure = __start.Int+3; /*tni_clock_3__cn_7*/
	_i_tni_clock_3__controller_tick = __start.Bool+2; /*tni_clock_3__cn_6*/
	_i_tni_clock_3__controller_B1 = tni_clock_3_B1;
	_i_tni_clock_3__controller_B2 = tni_clock_3_B2;
	_i_tni_clock_3__controller_B3 = tni_clock_3_B3;
	_i_tni_clock_3__controller_B4 = tni_clock_3_B4;
	_i_tni_clock_3__controller_displayValue = __start.Bool+3; /*tni_clock_3__cn_5*/
	_i_tni_clock_3__controller_stepMotorSecond = __start.Bool+4; /*tni_clock_3__cn_4*/
	_i_tni_clock_3__controller_stepMotorMinute = __start.Bool+5; /*tni_clock_3__cn_3*/
	_i_tni_clock_3__controller_stepMotorHour = __start.Bool+6; /*tni_clock_3__cn_2*/
	_i_tni_clock_3__controller_switchOnLight = __start.Bool+7; /*tni_clock_3__cn_1*/
	_my_app__controller_init();

	/*initialize child LCD (my_app.lcd):*/
	self_num++;
	my_app__tni_clock_3_offset_LCD.Bool = self.Bool - __start.Bool;
	my_app__tni_clock_3_offset_LCD.Int = self.Int - __start.Int;
	my_app__tni_clock_3_offset_LCD.Float = self.Float - __start.Float;
	my_app__tni_clock_3_offset_LCD.Char = self.Char - __start.Char;
	_i_tni_clock_3__lcd_displayValue = __start.Bool+3; /*tni_clock_3__cn_5*/
	_i_tni_clock_3__lcd_displayString = __start.Bool+1; /*tni_clock_3__cn_10*/
	_i_tni_clock_3__lcd_i = __start.Bool+0; /*tni_clock_3__cn_11*/
	_my_app__lcd_init();

	/*initialize child motors (my_app.motors):*/
	self_num++;
	my_app__tni_clock_3_offset_motors.Bool = self.Bool - __start.Bool;
	my_app__tni_clock_3_offset_motors.Int = self.Int - __start.Int;
	my_app__tni_clock_3_offset_motors.Float = self.Float - __start.Float;
	my_app__tni_clock_3_offset_motors.Char = self.Char - __start.Char;
	_i_tni_clock_3__motors_stepMotorSecond = __start.Bool+4; /*tni_clock_3__cn_4*/
	_i_tni_clock_3__motors_stepMotorMinute = __start.Bool+5; /*tni_clock_3__cn_3*/
	_i_tni_clock_3__motors_stepMotorHour = __start.Bool+6; /*tni_clock_3__cn_2*/
	_i_tni_clock_3__motors_hourHand = __start.Int+2; /*tni_clock_3__cn_12*/
	_i_tni_clock_3__motors_minuteHand = __start.Int+1; /*tni_clock_3__cn_13*/
	_i_tni_clock_3__motors_secondHand = __start.Int+0; /*tni_clock_3__cn_14*/
	_my_app__motors_init();

	/*initialize child light (my_app.light):*/
	self_num++;
	my_app__tni_clock_3_offset_light.Bool = self.Bool - __start.Bool;
	my_app__tni_clock_3_offset_light.Int = self.Int - __start.Int;
	my_app__tni_clock_3_offset_light.Float = self.Float - __start.Float;
	my_app__tni_clock_3_offset_light.Char = self.Char - __start.Char;
	_i_tni_clock_3__light_switchOnLight = __start.Bool+7; /*tni_clock_3__cn_1*/
	_my_app__light_init();

	my_app__tni_clock_3_offset__end.Bool = self.Bool - __start.Bool;
	my_app__tni_clock_3_offset__end.Int = self.Int - __start.Int;
	my_app__tni_clock_3_offset__end.Float = self.Float - __start.Float;
	my_app__tni_clock_3_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int my_app__tni_clock_3(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																												
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__tni_clock_3_offset_environment.Bool;
			self.Int = __start.Int + my_app__tni_clock_3_offset_environment.Int;
			self.Float = __start.Float + my_app__tni_clock_3_offset_environment.Float;
			self.Char = __start.Char + my_app__tni_clock_3_offset_environment.Char;

			/********************** environment execution ***********************/

			self_num++;
			if (environment__num != self_num) {
				environment__num = self_num;
				_i_tni_clock_3__environment_depth = tni_clock_3_depth;
				_i_tni_clock_3__environment_B1 = tni_clock_3_B1;
				_i_tni_clock_3__environment_B2 = tni_clock_3_B2;
				_i_tni_clock_3__environment_B3 = tni_clock_3_B3;
				_i_tni_clock_3__environment_B4 = tni_clock_3_B4;
				_i_tni_clock_3__environment_hydrostaticPressure = __start.Float+1; /*tni_clock_3__cn_8*/
				_i_tni_clock_3__environment_absolutePressure = __start.Float+0; /*tni_clock_3__cn_9*/
				_i_tni_clock_3__environment_pressure = __start.Int+3; /*tni_clock_3__cn_7*/
				_i_tni_clock_3__environment_tick = __start.Bool+2; /*tni_clock_3__cn_6*/
			}
			__ret = my_app__environment();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** controller execution ***********************/

			self_num++;
			if (controller__num != self_num) {
				controller__num = self_num;
				_i_tni_clock_3__controller_pressure = __start.Int+3; /*tni_clock_3__cn_7*/
				_i_tni_clock_3__controller_tick = __start.Bool+2; /*tni_clock_3__cn_6*/
				_i_tni_clock_3__controller_B1 = tni_clock_3_B1;
				_i_tni_clock_3__controller_B2 = tni_clock_3_B2;
				_i_tni_clock_3__controller_B3 = tni_clock_3_B3;
				_i_tni_clock_3__controller_B4 = tni_clock_3_B4;
				_i_tni_clock_3__controller_displayValue = __start.Bool+3; /*tni_clock_3__cn_5*/
				_i_tni_clock_3__controller_stepMotorSecond = __start.Bool+4; /*tni_clock_3__cn_4*/
				_i_tni_clock_3__controller_stepMotorMinute = __start.Bool+5; /*tni_clock_3__cn_3*/
				_i_tni_clock_3__controller_stepMotorHour = __start.Bool+6; /*tni_clock_3__cn_2*/
				_i_tni_clock_3__controller_switchOnLight = __start.Bool+7; /*tni_clock_3__cn_1*/
			}
			__ret = my_app__controller();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** LCD execution ***************************/

			self_num++;
			if (lcd__num != self_num) {
				lcd__num = self_num;
				_i_tni_clock_3__lcd_displayValue = __start.Bool+3; /*tni_clock_3__cn_5*/
				_i_tni_clock_3__lcd_displayString = __start.Bool+1; /*tni_clock_3__cn_10*/
				_i_tni_clock_3__lcd_i = __start.Bool+0; /*tni_clock_3__cn_11*/
			}
			__ret = my_app__lcd();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* motors execution *************************/

			self_num++;
			if (motors__num != self_num) {
				motors__num = self_num;
				_i_tni_clock_3__motors_stepMotorSecond = __start.Bool+4; /*tni_clock_3__cn_4*/
				_i_tni_clock_3__motors_stepMotorMinute = __start.Bool+5; /*tni_clock_3__cn_3*/
				_i_tni_clock_3__motors_stepMotorHour = __start.Bool+6; /*tni_clock_3__cn_2*/
				_i_tni_clock_3__motors_hourHand = __start.Int+2; /*tni_clock_3__cn_12*/
				_i_tni_clock_3__motors_minuteHand = __start.Int+1; /*tni_clock_3__cn_13*/
				_i_tni_clock_3__motors_secondHand = __start.Int+0; /*tni_clock_3__cn_14*/
			}
			__ret = my_app__motors();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* light execution **************************/

			self_num++;
			if (light__num != self_num) {
				light__num = self_num;
				_i_tni_clock_3__light_switchOnLight = __start.Bool+7; /*tni_clock_3__cn_1*/
			}
			__ret = my_app__light();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__tni_clock_3_offset__end.Bool;
	self.Int = __start.Int + my_app__tni_clock_3_offset__end.Int;
	self.Float = __start.Float + my_app__tni_clock_3_offset__end.Float;
	self.Char = __start.Char + my_app__tni_clock_3_offset__end.Char;

	return 0;
}

