/*2024-03-18T15:45:01-01:00*/

/********************************************************************
 * drill.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__DRILL_H
#define _MY_APP__DRILL_H


/********************** Variable declarations ***********************/

extern CB_Index drill__num;

/********************** Function declarations ***********************/

extern int _my_app__drill_init(void);
extern int my_app__drill(void);

#endif /*_MY_APP__DRILL_H*/
