/*2024-03-14T15:54:11-01:00*/

/********************************************************************
 * top.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__TOP_H
#define _MY_APP__TOP_H


/********************** Variable declarations ***********************/

extern CB_Index top__num;

/********************** Function declarations ***********************/

extern int _my_app__top_init(void);
extern int my_app__top(void);

#endif /*_MY_APP__TOP_H*/
