/*2024-03-14T15:54:11-01:00*/

/********************************************************************
 * top.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"


/********************************************************************
 *                     Inner 'a1' declarations                      *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index a1__num;

/********************** Function declarations ***********************/

static int _my_app__a1_init(void);
static int my_app__a1(void);

/********************************************************************
 *                     Inner 'a2' declarations                      *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index a2__num;

/********************** Function declarations ***********************/

static int _my_app__a2_init(void);
static int my_app__a2(void);

/********************************************************************
 *                     Inner 'a3' declarations                      *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index a3__num;

/********************** Function declarations ***********************/

static int _my_app__a3_init(void);
static int my_app__a3(void);

/********************************************************************
 *                   Inner 'sub_pou' declarations                   *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index sub_pou__num;

/********************** Function declarations ***********************/

static int _my_app__sub_pou_init(void);
static int my_app__sub_pou(void);

/********************************************************************
 *                    Inner 'a1' implementation                     *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index a1__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__a1_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__a1(void)
{
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}


/********************************************************************
 *                    Inner 'a2' implementation                     *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index a2__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__a2_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__a2(void)
{
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}


/********************************************************************
 *                    Inner 'a3' implementation                     *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index a3__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__a3_offset_sub_pou1;
static CB_Offset my_app__a3_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__a3_init(void)
{
	CB_Object __start = self;

	/*initialize child sub_pou1 (my_app.sub_pou):*/
	self_num++;
	my_app__a3_offset_sub_pou1.Bool = self.Bool - __start.Bool;
	my_app__a3_offset_sub_pou1.Int = self.Int - __start.Int;
	my_app__a3_offset_sub_pou1.Float = self.Float - __start.Float;
	my_app__a3_offset_sub_pou1.Char = self.Char - __start.Char;
	_my_app__sub_pou_init();

	my_app__a3_offset__end.Bool = self.Bool - __start.Bool;
	my_app__a3_offset__end.Int = self.Int - __start.Int;
	my_app__a3_offset__end.Float = self.Float - __start.Float;
	my_app__a3_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__a3(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__a3_offset_sub_pou1.Bool;
			self.Int = __start.Int + my_app__a3_offset_sub_pou1.Int;
			self.Float = __start.Float + my_app__a3_offset_sub_pou1.Float;
			self.Char = __start.Char + my_app__a3_offset_sub_pou1.Char;

			/************************ sub_pou1 execution ************************/

			self_num++;
			if (sub_pou__num != self_num) {
				sub_pou__num = self_num;
			}
			__ret = my_app__sub_pou();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__a3_offset__end.Bool;
	self.Int = __start.Int + my_app__a3_offset__end.Int;
	self.Float = __start.Float + my_app__a3_offset__end.Float;
	self.Char = __start.Char + my_app__a3_offset__end.Char;

	return 0;
}


/********************************************************************
 *                  Inner 'sub_pou' implementation                  *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index sub_pou__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__sub_pou_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__sub_pou(void)
{
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}


/********************************************************************
 *                Public 'my_app.top' implementation                *
 ********************************************************************/

#include "top.h"


/**************************** Variables *****************************/

CB_Index top__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__top_offset_a11;
static CB_Offset my_app__top_offset_a21;
static CB_Offset my_app__top_offset_a31;
static CB_Offset my_app__top_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _my_app__top_init(void)
{
	CB_Object __start = self;

	/*initialize child a11 (my_app.a1):*/
	self_num++;
	my_app__top_offset_a11.Bool = self.Bool - __start.Bool;
	my_app__top_offset_a11.Int = self.Int - __start.Int;
	my_app__top_offset_a11.Float = self.Float - __start.Float;
	my_app__top_offset_a11.Char = self.Char - __start.Char;
	_my_app__a1_init();

	/*initialize child a21 (my_app.a2):*/
	self_num++;
	my_app__top_offset_a21.Bool = self.Bool - __start.Bool;
	my_app__top_offset_a21.Int = self.Int - __start.Int;
	my_app__top_offset_a21.Float = self.Float - __start.Float;
	my_app__top_offset_a21.Char = self.Char - __start.Char;
	_my_app__a2_init();

	/*initialize child a31 (my_app.a3):*/
	self_num++;
	my_app__top_offset_a31.Bool = self.Bool - __start.Bool;
	my_app__top_offset_a31.Int = self.Int - __start.Int;
	my_app__top_offset_a31.Float = self.Float - __start.Float;
	my_app__top_offset_a31.Char = self.Char - __start.Char;
	_my_app__a3_init();

	my_app__top_offset__end.Bool = self.Bool - __start.Bool;
	my_app__top_offset__end.Int = self.Int - __start.Int;
	my_app__top_offset__end.Float = self.Float - __start.Float;
	my_app__top_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int my_app__top(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__top_offset_a11.Bool;
			self.Int = __start.Int + my_app__top_offset_a11.Int;
			self.Float = __start.Float + my_app__top_offset_a11.Float;
			self.Char = __start.Char + my_app__top_offset_a11.Char;

			/************************** a11 execution ***************************/

			self_num++;
			if (a1__num != self_num) {
				a1__num = self_num;
			}
			__ret = my_app__a1();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** a21 execution ***************************/

			self_num++;
			if (a2__num != self_num) {
				a2__num = self_num;
			}
			__ret = my_app__a2();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** a31 execution ***************************/

			self_num++;
			if (a3__num != self_num) {
				a3__num = self_num;
			}
			__ret = my_app__a3();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__top_offset__end.Bool;
	self.Int = __start.Int + my_app__top_offset__end.Int;
	self.Float = __start.Float + my_app__top_offset__end.Float;
	self.Char = __start.Char + my_app__top_offset__end.Char;

	return 0;
}

