/*2024-03-13T17:20:51-01:00*/

/********************************************************************
 * rootsystem.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__ROOTSYSTEM_H
#define _MY_APP__ROOTSYSTEM_H


/********************** Variable declarations ***********************/

extern CB_Index rootsystem__num;
extern CB_Mem_Float *rootsystem_aaaaa;
extern CB_Mem_Float *rootsystem_bbbb;

/********************** Function declarations ***********************/

extern int _my_app__rootsystem_init(void);
extern int my_app__rootsystem(void);

#endif /*_MY_APP__ROOTSYSTEM_H*/
