/*2024-03-13T17:20:51-01:00*/

/********************************************************************
 * rootsystem.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"


/********************************************************************
 *                     Inner 'mac' declarations                     *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index mac__num;
extern CB_Mem_Float *_i_rootsystem__mac_con;

/********************** Function declarations ***********************/

static int _my_app__mac_init(void);
static int my_app__mac(void);

/********************************************************************
 *                    Inner 'mac' implementation                    *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index mac__num = 0;
CB_Mem_Float *_i_rootsystem__mac_con;

/**************************** Variables *****************************/



/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__mac_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__mac(void)
{
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}


/********************************************************************
 *            Public 'my_app.rootsystem' implementation             *
 ********************************************************************/

#include "rootsystem.h"


/**************************** Variables *****************************/

CB_Index rootsystem__num = 0;
CB_Mem_Float *rootsystem_aaaaa;
CB_Mem_Float *rootsystem_bbbb;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__rootsystem_offset_mac;
static CB_Offset my_app__rootsystem_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _my_app__rootsystem_init(void)
{
	CB_Object __start = self;

	/*initialize child mac (my_app.mac):*/
	self_num++;
	my_app__rootsystem_offset_mac.Bool = self.Bool - __start.Bool;
	my_app__rootsystem_offset_mac.Int = self.Int - __start.Int;
	my_app__rootsystem_offset_mac.Float = self.Float - __start.Float;
	my_app__rootsystem_offset_mac.Char = self.Char - __start.Char;
	_i_rootsystem__mac_con = rootsystem_aaaaa;
	_my_app__mac_init();

	my_app__rootsystem_offset__end.Bool = self.Bool - __start.Bool;
	my_app__rootsystem_offset__end.Int = self.Int - __start.Int;
	my_app__rootsystem_offset__end.Float = self.Float - __start.Float;
	my_app__rootsystem_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int my_app__rootsystem(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__rootsystem_offset_mac.Bool;
			self.Int = __start.Int + my_app__rootsystem_offset_mac.Int;
			self.Float = __start.Float + my_app__rootsystem_offset_mac.Float;
			self.Char = __start.Char + my_app__rootsystem_offset_mac.Char;

			/************************** mac execution ***************************/

			self_num++;
			if (mac__num != self_num) {
				mac__num = self_num;
				_i_rootsystem__mac_con = rootsystem_aaaaa;
			}
			__ret = my_app__mac();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__rootsystem_offset__end.Bool;
	self.Int = __start.Int + my_app__rootsystem_offset__end.Int;
	self.Float = __start.Float + my_app__rootsystem_offset__end.Float;
	self.Char = __start.Char + my_app__rootsystem_offset__end.Char;

	return 0;
}

