/*2024-03-14T10:01:27-01:00*/

/********************************************************************
 * my_app_1_2.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__MY_APP_1_2_H
#define _MY_APP__MY_APP_1_2_H


/********************** Variable declarations ***********************/

extern CB_Index my_app_1_2__num;
extern CB_Mem_Bool *my_app_1_2_entree;

/********************** Function declarations ***********************/

extern int _my_app__my_app_1_2_init(void);
extern int my_app__my_app_1_2(void);

#endif /*_MY_APP__MY_APP_1_2_H*/
