/*2024-03-13T18:07:39-01:00*/

/********************************************************************
 * my_app_1_1.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__MY_APP_1_1_H
#define _MY_APP__MY_APP_1_1_H


/********************** Variable declarations ***********************/

extern CB_Index my_app_1_1__num;
extern CB_Mem_Bool *my_app_1_1_entree;

/********************** Function declarations ***********************/

extern int _my_app__my_app_1_1_init(void);
extern int my_app__my_app_1_1(void);

#endif /*_MY_APP__MY_APP_1_1_H*/
