/*2024-03-13T17:22:31-01:00*/

/********************************************************************
 * my_app.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__MY_APP_H
#define _MY_APP__MY_APP_H


/********************** Variable declarations ***********************/

extern CB_Index my_app__num;
extern CB_Mem_Bool *my_app_entree;

/********************** Function declarations ***********************/

extern int _my_app__my_app_init(void);
extern int my_app__my_app(void);

#endif /*_MY_APP__MY_APP_H*/
