/*2024-03-18T11:53:50-01:00*/

/********************************************************************
 * dc_motor2023_1.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"


/********************************************************************
 *              Inner 'dc_motor_mechanic' declarations              *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index dc_motor_mechanic__num;
extern CB_Mem_Float *_i_dc_motor2023_1__dc_motor_mechanic_M;
extern CB_Mem_Float *_i_dc_motor2023_1__dc_motor_mechanic_wB;

/********************** Function declarations ***********************/

static int _my_app__dc_motor_mechanic_init(void);
static int my_app__dc_motor_mechanic(void);

/********************************************************************
 *                Inner 'stimuli_model' declarations                *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index stimuli_model__num;
extern CB_Mem_Float *_i_dc_motor2023_1__stimuli_model_M_load;
extern CB_Mem_Float *_i_dc_motor2023_1__stimuli_model_U;

/********************** Function declarations ***********************/

static int _my_app__stimuli_model_init(void);
static int my_app__stimuli_model(void);

/********************************************************************
 *                 Inner 'edrive_mass' declarations                 *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index edrive_mass__num;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_M_A;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_M_B;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_wA;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_wB;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_phiB;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_phiA;

/********************** Function declarations ***********************/

static int _my_app__edrive_mass_init(void);
static int my_app__edrive_mass(void);

/********************************************************************
 *     Inner 'design_specification_dc_motor_model' declarations     *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index design_specification_dc_motor_model__num;
extern CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_I;
extern CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_U;
extern CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_M_mot;
extern CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_wB;

/********************** Function declarations ***********************/

static int _my_app__design_specification_dc_motor_model_init(void);
static int my_app__design_specification_dc_motor_model(void);

/********************************************************************
 *                     Inner 'sut' declarations                     *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index sut__num;
extern CB_Mem_Float *_i_dc_motor2023_1__sut_M_load;
extern CB_Mem_Float *_i_dc_motor2023_1__sut_U;
extern CB_Mem_Float *_i_dc_motor2023_1__sut_phiB;
extern CB_Mem_Float *_i_dc_motor2023_1__sut_M_mot;
extern CB_Mem_Float *_i_dc_motor2023_1__sut_I;
extern CB_Mem_Float *_i_dc_motor2023_1__sut_wB;

/********************** Function declarations ***********************/

static int _my_app__sut_init(void);
static int my_app__sut(void);

/********************************************************************
 *               Inner 'emachine_model' declarations                *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index emachine_model__num;
extern CB_Mem_Float *_i_dc_motor2023_1__emachine_model_phi;
extern CB_Mem_Float *_i_dc_motor2023_1__emachine_model_U;
extern CB_Mem_Float *_i_dc_motor2023_1__emachine_model_w;
extern CB_Mem_Float *_i_dc_motor2023_1__emachine_model_I;
extern CB_Mem_Float *_i_dc_motor2023_1__emachine_model_M;

/********************** Function declarations ***********************/

static int _my_app__emachine_model_init(void);
static int my_app__emachine_model(void);

/********************************************************************
 *              Inner 'edrive_mass_spec' declarations               *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index edrive_mass_spec__num;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_M_A;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_M_B;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_wA;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_phiB;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_phiA;
extern CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_wB;

/********************** Function declarations ***********************/

static int _my_app__edrive_mass_spec_init(void);
static int my_app__edrive_mass_spec(void);

/********************************************************************
 *                  Inner 'dc_motor' declarations                   *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index dc_motor__num;
extern CB_Mem_Float *_i_dc_motor2023_1__dc_motor_M_mot;
extern CB_Mem_Float *_i_dc_motor2023_1__dc_motor_wB;
extern CB_Mem_Float *_i_dc_motor2023_1__dc_motor_U;
extern CB_Mem_Float *_i_dc_motor2023_1__dc_motor_I;

/********************** Function declarations ***********************/

static int _my_app__dc_motor_init(void);
static int my_app__dc_motor(void);

/********************************************************************
 *             Inner 'dc_motor_mechanic' implementation             *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index dc_motor_mechanic__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__dc_motor_mechanic_M;
CB_Mem_Float *_i_dc_motor2023_1__dc_motor_mechanic_wB;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__dc_motor_mechanic_offset_stimuli_model;
static CB_Offset my_app__dc_motor_mechanic_offset_edrive_mass;
static CB_Offset my_app__dc_motor_mechanic_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__dc_motor_mechanic_init(void)
{
	CB_Object __start = self;
	self.Float+=5;

	/*initialize child stimuli_model (my_app.stimuli_model):*/
	self_num++;
	my_app__dc_motor_mechanic_offset_stimuli_model.Bool = self.Bool - __start.Bool;
	my_app__dc_motor_mechanic_offset_stimuli_model.Int = self.Int - __start.Int;
	my_app__dc_motor_mechanic_offset_stimuli_model.Float = self.Float - __start.Float;
	my_app__dc_motor_mechanic_offset_stimuli_model.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__stimuli_model_M_load = _i_dc_motor2023_1__dc_motor_mechanic_M;
	_i_dc_motor2023_1__stimuli_model_U = __start.Float+4; /*dc_motor_mechanic__cn_1*/
	_my_app__stimuli_model_init();

	/*initialize child edrive_mass (my_app.edrive_mass):*/
	self_num++;
	my_app__dc_motor_mechanic_offset_edrive_mass.Bool = self.Bool - __start.Bool;
	my_app__dc_motor_mechanic_offset_edrive_mass.Int = self.Int - __start.Int;
	my_app__dc_motor_mechanic_offset_edrive_mass.Float = self.Float - __start.Float;
	my_app__dc_motor_mechanic_offset_edrive_mass.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__edrive_mass_M_A = _i_dc_motor2023_1__dc_motor_mechanic_M;
	_i_dc_motor2023_1__edrive_mass_M_B = __start.Float+3; /*dc_motor_mechanic__cn_2*/
	_i_dc_motor2023_1__edrive_mass_wA = __start.Float+2; /*dc_motor_mechanic__cn_3*/
	_i_dc_motor2023_1__edrive_mass_wB = _i_dc_motor2023_1__dc_motor_mechanic_wB;
	_i_dc_motor2023_1__edrive_mass_phiB = __start.Float+1; /*dc_motor_mechanic__cn_4*/
	_i_dc_motor2023_1__edrive_mass_phiA = __start.Float+0; /*dc_motor_mechanic__cn_5*/
	_my_app__edrive_mass_init();

	my_app__dc_motor_mechanic_offset__end.Bool = self.Bool - __start.Bool;
	my_app__dc_motor_mechanic_offset__end.Int = self.Int - __start.Int;
	my_app__dc_motor_mechanic_offset__end.Float = self.Float - __start.Float;
	my_app__dc_motor_mechanic_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__dc_motor_mechanic(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

										
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__dc_motor_mechanic_offset_stimuli_model.Bool;
			self.Int = __start.Int + my_app__dc_motor_mechanic_offset_stimuli_model.Int;
			self.Float = __start.Float + my_app__dc_motor_mechanic_offset_stimuli_model.Float;
			self.Char = __start.Char + my_app__dc_motor_mechanic_offset_stimuli_model.Char;

			/********************* stimuli_model execution **********************/

			self_num++;
			if (stimuli_model__num != self_num) {
				stimuli_model__num = self_num;
				_i_dc_motor2023_1__stimuli_model_M_load = _i_dc_motor2023_1__dc_motor_mechanic_M;
				_i_dc_motor2023_1__stimuli_model_U = __start.Float+4; /*dc_motor_mechanic__cn_1*/
			}
			__ret = my_app__stimuli_model();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** edrive_mass execution ***********************/

			self_num++;
			if (edrive_mass__num != self_num) {
				edrive_mass__num = self_num;
				_i_dc_motor2023_1__edrive_mass_M_A = _i_dc_motor2023_1__dc_motor_mechanic_M;
				_i_dc_motor2023_1__edrive_mass_M_B = __start.Float+3; /*dc_motor_mechanic__cn_2*/
				_i_dc_motor2023_1__edrive_mass_wA = __start.Float+2; /*dc_motor_mechanic__cn_3*/
				_i_dc_motor2023_1__edrive_mass_wB = _i_dc_motor2023_1__dc_motor_mechanic_wB;
				_i_dc_motor2023_1__edrive_mass_phiB = __start.Float+1; /*dc_motor_mechanic__cn_4*/
				_i_dc_motor2023_1__edrive_mass_phiA = __start.Float+0; /*dc_motor_mechanic__cn_5*/
			}
			__ret = my_app__edrive_mass();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__dc_motor_mechanic_offset__end.Bool;
	self.Int = __start.Int + my_app__dc_motor_mechanic_offset__end.Int;
	self.Float = __start.Float + my_app__dc_motor_mechanic_offset__end.Float;
	self.Char = __start.Char + my_app__dc_motor_mechanic_offset__end.Char;

	return 0;
}


/********************************************************************
 *               Inner 'stimuli_model' implementation               *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index stimuli_model__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__stimuli_model_M_load;
CB_Mem_Float *_i_dc_motor2023_1__stimuli_model_U;

/**************************** Variables *****************************/

#define M_load (_i_dc_motor2023_1__stimuli_model_M_load->CB_current_value)
#define U (_i_dc_motor2023_1__stimuli_model_U->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__stimuli_model_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__stimuli_model(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_float(_i_dc_motor2023_1__stimuli_model_M_load);
		CB_post_float(_i_dc_motor2023_1__stimuli_model_U);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef M_load
#undef U

/********************************************************************
 *                Inner 'edrive_mass' implementation                *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index edrive_mass__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_M_A;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_M_B;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_wA;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_wB;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_phiB;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_phiA;

/**************************** Variables *****************************/

#define M_A (_i_dc_motor2023_1__edrive_mass_M_A->CB_current_value)
#define M_B (_i_dc_motor2023_1__edrive_mass_M_B->CB_current_value)
#define wA (_i_dc_motor2023_1__edrive_mass_wA->CB_current_value)
#define wB (_i_dc_motor2023_1__edrive_mass_wB->CB_current_value)
#define phiB (_i_dc_motor2023_1__edrive_mass_phiB->CB_current_value)
#define phiA (_i_dc_motor2023_1__edrive_mass_phiA->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__edrive_mass_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__edrive_mass(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_float(_i_dc_motor2023_1__edrive_mass_wA);
		CB_post_float(_i_dc_motor2023_1__edrive_mass_wB);
		CB_post_float(_i_dc_motor2023_1__edrive_mass_phiB);
		CB_post_float(_i_dc_motor2023_1__edrive_mass_phiA);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef M_A
#undef M_B
#undef wA
#undef wB
#undef phiB
#undef phiA

/********************************************************************
 *    Inner 'design_specification_dc_motor_model' implementation    *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index design_specification_dc_motor_model__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_I;
CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_U;
CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_M_mot;
CB_Mem_Float *_i_dc_motor2023_1__design_specification_dc_motor_model_wB;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__design_specification_dc_motor_model_offset_SuT;
static CB_Offset my_app__design_specification_dc_motor_model_offset_stimuli_model;
static CB_Offset my_app__design_specification_dc_motor_model_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__design_specification_dc_motor_model_init(void)
{
	CB_Object __start = self;
	self.Float+=2;

	/*initialize child SuT (my_app.sut):*/
	self_num++;
	my_app__design_specification_dc_motor_model_offset_SuT.Bool = self.Bool - __start.Bool;
	my_app__design_specification_dc_motor_model_offset_SuT.Int = self.Int - __start.Int;
	my_app__design_specification_dc_motor_model_offset_SuT.Float = self.Float - __start.Float;
	my_app__design_specification_dc_motor_model_offset_SuT.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__sut_M_load = __start.Float+1; /*design_specification_dc_motor_model__cn_1*/
	_i_dc_motor2023_1__sut_U = _i_dc_motor2023_1__design_specification_dc_motor_model_U;
	_i_dc_motor2023_1__sut_phiB = __start.Float+0; /*design_specification_dc_motor_model__cn_2*/
	_i_dc_motor2023_1__sut_M_mot = _i_dc_motor2023_1__design_specification_dc_motor_model_M_mot;
	_i_dc_motor2023_1__sut_I = _i_dc_motor2023_1__design_specification_dc_motor_model_I;
	_i_dc_motor2023_1__sut_wB = _i_dc_motor2023_1__design_specification_dc_motor_model_wB;
	_my_app__sut_init();

	/*initialize child stimuli_model (my_app.stimuli_model):*/
	self_num++;
	my_app__design_specification_dc_motor_model_offset_stimuli_model.Bool = self.Bool - __start.Bool;
	my_app__design_specification_dc_motor_model_offset_stimuli_model.Int = self.Int - __start.Int;
	my_app__design_specification_dc_motor_model_offset_stimuli_model.Float = self.Float - __start.Float;
	my_app__design_specification_dc_motor_model_offset_stimuli_model.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__stimuli_model_M_load = __start.Float+1; /*design_specification_dc_motor_model__cn_1*/
	_i_dc_motor2023_1__stimuli_model_U = _i_dc_motor2023_1__design_specification_dc_motor_model_U;
	_my_app__stimuli_model_init();

	my_app__design_specification_dc_motor_model_offset__end.Bool = self.Bool - __start.Bool;
	my_app__design_specification_dc_motor_model_offset__end.Int = self.Int - __start.Int;
	my_app__design_specification_dc_motor_model_offset__end.Float = self.Float - __start.Float;
	my_app__design_specification_dc_motor_model_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__design_specification_dc_motor_model(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

				
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__design_specification_dc_motor_model_offset_SuT.Bool;
			self.Int = __start.Int + my_app__design_specification_dc_motor_model_offset_SuT.Int;
			self.Float = __start.Float + my_app__design_specification_dc_motor_model_offset_SuT.Float;
			self.Char = __start.Char + my_app__design_specification_dc_motor_model_offset_SuT.Char;

			/************************** SuT execution ***************************/

			self_num++;
			if (sut__num != self_num) {
				sut__num = self_num;
				_i_dc_motor2023_1__sut_M_load = __start.Float+1; /*design_specification_dc_motor_model__cn_1*/
				_i_dc_motor2023_1__sut_U = _i_dc_motor2023_1__design_specification_dc_motor_model_U;
				_i_dc_motor2023_1__sut_phiB = __start.Float+0; /*design_specification_dc_motor_model__cn_2*/
				_i_dc_motor2023_1__sut_M_mot = _i_dc_motor2023_1__design_specification_dc_motor_model_M_mot;
				_i_dc_motor2023_1__sut_I = _i_dc_motor2023_1__design_specification_dc_motor_model_I;
				_i_dc_motor2023_1__sut_wB = _i_dc_motor2023_1__design_specification_dc_motor_model_wB;
			}
			__ret = my_app__sut();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* stimuli_model execution **********************/

			self_num++;
			if (stimuli_model__num != self_num) {
				stimuli_model__num = self_num;
				_i_dc_motor2023_1__stimuli_model_M_load = __start.Float+1; /*design_specification_dc_motor_model__cn_1*/
				_i_dc_motor2023_1__stimuli_model_U = _i_dc_motor2023_1__design_specification_dc_motor_model_U;
			}
			__ret = my_app__stimuli_model();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__design_specification_dc_motor_model_offset__end.Bool;
	self.Int = __start.Int + my_app__design_specification_dc_motor_model_offset__end.Int;
	self.Float = __start.Float + my_app__design_specification_dc_motor_model_offset__end.Float;
	self.Char = __start.Char + my_app__design_specification_dc_motor_model_offset__end.Char;

	return 0;
}


/********************************************************************
 *                    Inner 'sut' implementation                    *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index sut__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__sut_M_load;
CB_Mem_Float *_i_dc_motor2023_1__sut_U;
CB_Mem_Float *_i_dc_motor2023_1__sut_phiB;
CB_Mem_Float *_i_dc_motor2023_1__sut_M_mot;
CB_Mem_Float *_i_dc_motor2023_1__sut_I;
CB_Mem_Float *_i_dc_motor2023_1__sut_wB;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__sut_offset_emachine_model;
static CB_Offset my_app__sut_offset_edrive_mass_spec;
static CB_Offset my_app__sut_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__sut_init(void)
{
	CB_Object __start = self;
	self.Float+=2;

	/*initialize child emachine_model (my_app.emachine_model):*/
	self_num++;
	my_app__sut_offset_emachine_model.Bool = self.Bool - __start.Bool;
	my_app__sut_offset_emachine_model.Int = self.Int - __start.Int;
	my_app__sut_offset_emachine_model.Float = self.Float - __start.Float;
	my_app__sut_offset_emachine_model.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__emachine_model_phi = __start.Float+0; /*sut__cn_2*/
	_i_dc_motor2023_1__emachine_model_U = _i_dc_motor2023_1__sut_U;
	_i_dc_motor2023_1__emachine_model_w = __start.Float+1; /*sut__cn_1*/
	_i_dc_motor2023_1__emachine_model_I = _i_dc_motor2023_1__sut_I;
	_i_dc_motor2023_1__emachine_model_M = _i_dc_motor2023_1__sut_M_mot;
	_my_app__emachine_model_init();

	/*initialize child edrive_mass_spec (my_app.edrive_mass_spec):*/
	self_num++;
	my_app__sut_offset_edrive_mass_spec.Bool = self.Bool - __start.Bool;
	my_app__sut_offset_edrive_mass_spec.Int = self.Int - __start.Int;
	my_app__sut_offset_edrive_mass_spec.Float = self.Float - __start.Float;
	my_app__sut_offset_edrive_mass_spec.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__edrive_mass_spec_M_A = _i_dc_motor2023_1__sut_M_mot;
	_i_dc_motor2023_1__edrive_mass_spec_M_B = _i_dc_motor2023_1__sut_M_load;
	_i_dc_motor2023_1__edrive_mass_spec_wA = __start.Float+1; /*sut__cn_1*/
	_i_dc_motor2023_1__edrive_mass_spec_phiB = _i_dc_motor2023_1__sut_phiB;
	_i_dc_motor2023_1__edrive_mass_spec_phiA = __start.Float+0; /*sut__cn_2*/
	_i_dc_motor2023_1__edrive_mass_spec_wB = _i_dc_motor2023_1__sut_wB;
	_my_app__edrive_mass_spec_init();

	my_app__sut_offset__end.Bool = self.Bool - __start.Bool;
	my_app__sut_offset__end.Int = self.Int - __start.Int;
	my_app__sut_offset__end.Float = self.Float - __start.Float;
	my_app__sut_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__sut(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

				
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__sut_offset_emachine_model.Bool;
			self.Int = __start.Int + my_app__sut_offset_emachine_model.Int;
			self.Float = __start.Float + my_app__sut_offset_emachine_model.Float;
			self.Char = __start.Char + my_app__sut_offset_emachine_model.Char;

			/********************* emachine_model execution *********************/

			self_num++;
			if (emachine_model__num != self_num) {
				emachine_model__num = self_num;
				_i_dc_motor2023_1__emachine_model_phi = __start.Float+0; /*sut__cn_2*/
				_i_dc_motor2023_1__emachine_model_U = _i_dc_motor2023_1__sut_U;
				_i_dc_motor2023_1__emachine_model_w = __start.Float+1; /*sut__cn_1*/
				_i_dc_motor2023_1__emachine_model_I = _i_dc_motor2023_1__sut_I;
				_i_dc_motor2023_1__emachine_model_M = _i_dc_motor2023_1__sut_M_mot;
			}
			__ret = my_app__emachine_model();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** edrive_mass_spec execution ********************/

			self_num++;
			if (edrive_mass_spec__num != self_num) {
				edrive_mass_spec__num = self_num;
				_i_dc_motor2023_1__edrive_mass_spec_M_A = _i_dc_motor2023_1__sut_M_mot;
				_i_dc_motor2023_1__edrive_mass_spec_M_B = _i_dc_motor2023_1__sut_M_load;
				_i_dc_motor2023_1__edrive_mass_spec_wA = __start.Float+1; /*sut__cn_1*/
				_i_dc_motor2023_1__edrive_mass_spec_phiB = _i_dc_motor2023_1__sut_phiB;
				_i_dc_motor2023_1__edrive_mass_spec_phiA = __start.Float+0; /*sut__cn_2*/
				_i_dc_motor2023_1__edrive_mass_spec_wB = _i_dc_motor2023_1__sut_wB;
			}
			__ret = my_app__edrive_mass_spec();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__sut_offset__end.Bool;
	self.Int = __start.Int + my_app__sut_offset__end.Int;
	self.Float = __start.Float + my_app__sut_offset__end.Float;
	self.Char = __start.Char + my_app__sut_offset__end.Char;

	return 0;
}


/********************************************************************
 *              Inner 'emachine_model' implementation               *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index emachine_model__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__emachine_model_phi;
CB_Mem_Float *_i_dc_motor2023_1__emachine_model_U;
CB_Mem_Float *_i_dc_motor2023_1__emachine_model_w;
CB_Mem_Float *_i_dc_motor2023_1__emachine_model_I;
CB_Mem_Float *_i_dc_motor2023_1__emachine_model_M;

/**************************** Variables *****************************/

#define phi (_i_dc_motor2023_1__emachine_model_phi->CB_current_value)
#define U (_i_dc_motor2023_1__emachine_model_U->CB_current_value)
#define w (_i_dc_motor2023_1__emachine_model_w->CB_current_value)
#define I (_i_dc_motor2023_1__emachine_model_I->CB_current_value)
#define M (_i_dc_motor2023_1__emachine_model_M->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__emachine_model_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__emachine_model(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_float(_i_dc_motor2023_1__emachine_model_I);
		CB_post_float(_i_dc_motor2023_1__emachine_model_M);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef phi
#undef U
#undef w
#undef I
#undef M

/********************************************************************
 *             Inner 'edrive_mass_spec' implementation              *
 ********************************************************************/




/**************************** Variables *****************************/

static CB_Index edrive_mass_spec__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_M_A;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_M_B;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_wA;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_phiB;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_phiA;
CB_Mem_Float *_i_dc_motor2023_1__edrive_mass_spec_wB;

/**************************** Variables *****************************/

#define M_A (_i_dc_motor2023_1__edrive_mass_spec_M_A->CB_current_value)
#define M_B (_i_dc_motor2023_1__edrive_mass_spec_M_B->CB_current_value)
#define wA (_i_dc_motor2023_1__edrive_mass_spec_wA->CB_current_value)
#define phiB (_i_dc_motor2023_1__edrive_mass_spec_phiB->CB_current_value)
#define phiA (_i_dc_motor2023_1__edrive_mass_spec_phiA->CB_current_value)
#define wB (_i_dc_motor2023_1__edrive_mass_spec_wB->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _my_app__edrive_mass_spec_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int my_app__edrive_mass_spec(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{

		}

		CB_post_float(_i_dc_motor2023_1__edrive_mass_spec_wA);
		CB_post_float(_i_dc_motor2023_1__edrive_mass_spec_phiB);
		CB_post_float(_i_dc_motor2023_1__edrive_mass_spec_phiA);
		CB_post_float(_i_dc_motor2023_1__edrive_mass_spec_wB);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef M_A
#undef M_B
#undef wA
#undef phiB
#undef phiA
#undef wB

/********************************************************************
 *                 Inner 'dc_motor' implementation                  *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index dc_motor__num = 0;
CB_Mem_Float *_i_dc_motor2023_1__dc_motor_M_mot;
CB_Mem_Float *_i_dc_motor2023_1__dc_motor_wB;
CB_Mem_Float *_i_dc_motor2023_1__dc_motor_U;
CB_Mem_Float *_i_dc_motor2023_1__dc_motor_I;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__dc_motor_offset_SuT;
static CB_Offset my_app__dc_motor_offset_stimuli_model;
static CB_Offset my_app__dc_motor_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _my_app__dc_motor_init(void)
{
	CB_Object __start = self;
	self.Float+=2;

	/*initialize child SuT (my_app.sut):*/
	self_num++;
	my_app__dc_motor_offset_SuT.Bool = self.Bool - __start.Bool;
	my_app__dc_motor_offset_SuT.Int = self.Int - __start.Int;
	my_app__dc_motor_offset_SuT.Float = self.Float - __start.Float;
	my_app__dc_motor_offset_SuT.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__sut_M_load = __start.Float+1; /*dc_motor__cn_1*/
	_i_dc_motor2023_1__sut_U = _i_dc_motor2023_1__dc_motor_U;
	_i_dc_motor2023_1__sut_phiB = __start.Float+0; /*dc_motor__cn_2*/
	_i_dc_motor2023_1__sut_M_mot = _i_dc_motor2023_1__dc_motor_M_mot;
	_i_dc_motor2023_1__sut_I = _i_dc_motor2023_1__dc_motor_I;
	_i_dc_motor2023_1__sut_wB = _i_dc_motor2023_1__dc_motor_wB;
	_my_app__sut_init();

	/*initialize child stimuli_model (my_app.stimuli_model):*/
	self_num++;
	my_app__dc_motor_offset_stimuli_model.Bool = self.Bool - __start.Bool;
	my_app__dc_motor_offset_stimuli_model.Int = self.Int - __start.Int;
	my_app__dc_motor_offset_stimuli_model.Float = self.Float - __start.Float;
	my_app__dc_motor_offset_stimuli_model.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__stimuli_model_M_load = __start.Float+1; /*dc_motor__cn_1*/
	_i_dc_motor2023_1__stimuli_model_U = _i_dc_motor2023_1__dc_motor_U;
	_my_app__stimuli_model_init();

	my_app__dc_motor_offset__end.Bool = self.Bool - __start.Bool;
	my_app__dc_motor_offset__end.Int = self.Int - __start.Int;
	my_app__dc_motor_offset__end.Float = self.Float - __start.Float;
	my_app__dc_motor_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int my_app__dc_motor(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

				
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__dc_motor_offset_SuT.Bool;
			self.Int = __start.Int + my_app__dc_motor_offset_SuT.Int;
			self.Float = __start.Float + my_app__dc_motor_offset_SuT.Float;
			self.Char = __start.Char + my_app__dc_motor_offset_SuT.Char;

			/************************** SuT execution ***************************/

			self_num++;
			if (sut__num != self_num) {
				sut__num = self_num;
				_i_dc_motor2023_1__sut_M_load = __start.Float+1; /*dc_motor__cn_1*/
				_i_dc_motor2023_1__sut_U = _i_dc_motor2023_1__dc_motor_U;
				_i_dc_motor2023_1__sut_phiB = __start.Float+0; /*dc_motor__cn_2*/
				_i_dc_motor2023_1__sut_M_mot = _i_dc_motor2023_1__dc_motor_M_mot;
				_i_dc_motor2023_1__sut_I = _i_dc_motor2023_1__dc_motor_I;
				_i_dc_motor2023_1__sut_wB = _i_dc_motor2023_1__dc_motor_wB;
			}
			__ret = my_app__sut();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* stimuli_model execution **********************/

			self_num++;
			if (stimuli_model__num != self_num) {
				stimuli_model__num = self_num;
				_i_dc_motor2023_1__stimuli_model_M_load = __start.Float+1; /*dc_motor__cn_1*/
				_i_dc_motor2023_1__stimuli_model_U = _i_dc_motor2023_1__dc_motor_U;
			}
			__ret = my_app__stimuli_model();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__dc_motor_offset__end.Bool;
	self.Int = __start.Int + my_app__dc_motor_offset__end.Int;
	self.Float = __start.Float + my_app__dc_motor_offset__end.Float;
	self.Char = __start.Char + my_app__dc_motor_offset__end.Char;

	return 0;
}


/********************************************************************
 *          Public 'my_app.dc_motor2023_1' implementation           *
 ********************************************************************/

#include "dc_motor2023_1.h"


/**************************** Variables *****************************/

CB_Index dc_motor2023_1__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset my_app__dc_motor2023_1_offset_DC_motor_mechanic;
static CB_Offset my_app__dc_motor2023_1_offset_Design_Specification_DC_Motor_Model;
static CB_Offset my_app__dc_motor2023_1_offset_DC_Motor;
static CB_Offset my_app__dc_motor2023_1_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _my_app__dc_motor2023_1_init(void)
{
	CB_Object __start = self;
	self.Float+=10;

	/*initialize child DC_motor_mechanic (my_app.dc_motor_mechanic):*/
	self_num++;
	my_app__dc_motor2023_1_offset_DC_motor_mechanic.Bool = self.Bool - __start.Bool;
	my_app__dc_motor2023_1_offset_DC_motor_mechanic.Int = self.Int - __start.Int;
	my_app__dc_motor2023_1_offset_DC_motor_mechanic.Float = self.Float - __start.Float;
	my_app__dc_motor2023_1_offset_DC_motor_mechanic.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__dc_motor_mechanic_M = __start.Float+9; /*dc_motor2023_1__cn_1*/
	_i_dc_motor2023_1__dc_motor_mechanic_wB = __start.Float+8; /*dc_motor2023_1__cn_2*/
	_my_app__dc_motor_mechanic_init();

	/*initialize child Design_Specification_DC_Motor_Model (my_app.design_specification_dc_motor_model):*/
	self_num++;
	my_app__dc_motor2023_1_offset_Design_Specification_DC_Motor_Model.Bool = self.Bool - __start.Bool;
	my_app__dc_motor2023_1_offset_Design_Specification_DC_Motor_Model.Int = self.Int - __start.Int;
	my_app__dc_motor2023_1_offset_Design_Specification_DC_Motor_Model.Float = self.Float - __start.Float;
	my_app__dc_motor2023_1_offset_Design_Specification_DC_Motor_Model.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__design_specification_dc_motor_model_I = __start.Float+7; /*dc_motor2023_1__cn_3*/
	_i_dc_motor2023_1__design_specification_dc_motor_model_U = __start.Float+6; /*dc_motor2023_1__cn_4*/
	_i_dc_motor2023_1__design_specification_dc_motor_model_M_mot = __start.Float+5; /*dc_motor2023_1__cn_5*/
	_i_dc_motor2023_1__design_specification_dc_motor_model_wB = __start.Float+4; /*dc_motor2023_1__cn_6*/
	_my_app__design_specification_dc_motor_model_init();

	/*initialize child DC_Motor (my_app.dc_motor):*/
	self_num++;
	my_app__dc_motor2023_1_offset_DC_Motor.Bool = self.Bool - __start.Bool;
	my_app__dc_motor2023_1_offset_DC_Motor.Int = self.Int - __start.Int;
	my_app__dc_motor2023_1_offset_DC_Motor.Float = self.Float - __start.Float;
	my_app__dc_motor2023_1_offset_DC_Motor.Char = self.Char - __start.Char;
	_i_dc_motor2023_1__dc_motor_M_mot = __start.Float+3; /*dc_motor2023_1__cn_7*/
	_i_dc_motor2023_1__dc_motor_wB = __start.Float+2; /*dc_motor2023_1__cn_8*/
	_i_dc_motor2023_1__dc_motor_U = __start.Float+1; /*dc_motor2023_1__cn_9*/
	_i_dc_motor2023_1__dc_motor_I = __start.Float+0; /*dc_motor2023_1__cn_10*/
	_my_app__dc_motor_init();

	my_app__dc_motor2023_1_offset__end.Bool = self.Bool - __start.Bool;
	my_app__dc_motor2023_1_offset__end.Int = self.Int - __start.Int;
	my_app__dc_motor2023_1_offset__end.Float = self.Float - __start.Float;
	my_app__dc_motor2023_1_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int my_app__dc_motor2023_1(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																				
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + my_app__dc_motor2023_1_offset_DC_motor_mechanic.Bool;
			self.Int = __start.Int + my_app__dc_motor2023_1_offset_DC_motor_mechanic.Int;
			self.Float = __start.Float + my_app__dc_motor2023_1_offset_DC_motor_mechanic.Float;
			self.Char = __start.Char + my_app__dc_motor2023_1_offset_DC_motor_mechanic.Char;

			/******************* DC_motor_mechanic execution ********************/

			self_num++;
			if (dc_motor_mechanic__num != self_num) {
				dc_motor_mechanic__num = self_num;
				_i_dc_motor2023_1__dc_motor_mechanic_M = __start.Float+9; /*dc_motor2023_1__cn_1*/
				_i_dc_motor2023_1__dc_motor_mechanic_wB = __start.Float+8; /*dc_motor2023_1__cn_2*/
			}
			__ret = my_app__dc_motor_mechanic();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********** Design_Specification_DC_Motor_Model execution ***********/

			self_num++;
			if (design_specification_dc_motor_model__num != self_num) {
				design_specification_dc_motor_model__num = self_num;
				_i_dc_motor2023_1__design_specification_dc_motor_model_I = __start.Float+7; /*dc_motor2023_1__cn_3*/
				_i_dc_motor2023_1__design_specification_dc_motor_model_U = __start.Float+6; /*dc_motor2023_1__cn_4*/
				_i_dc_motor2023_1__design_specification_dc_motor_model_M_mot = __start.Float+5; /*dc_motor2023_1__cn_5*/
				_i_dc_motor2023_1__design_specification_dc_motor_model_wB = __start.Float+4; /*dc_motor2023_1__cn_6*/
			}
			__ret = my_app__design_specification_dc_motor_model();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ DC_Motor execution ************************/

			self_num++;
			if (dc_motor__num != self_num) {
				dc_motor__num = self_num;
				_i_dc_motor2023_1__dc_motor_M_mot = __start.Float+3; /*dc_motor2023_1__cn_7*/
				_i_dc_motor2023_1__dc_motor_wB = __start.Float+2; /*dc_motor2023_1__cn_8*/
				_i_dc_motor2023_1__dc_motor_U = __start.Float+1; /*dc_motor2023_1__cn_9*/
				_i_dc_motor2023_1__dc_motor_I = __start.Float+0; /*dc_motor2023_1__cn_10*/
			}
			__ret = my_app__dc_motor();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + my_app__dc_motor2023_1_offset__end.Bool;
	self.Int = __start.Int + my_app__dc_motor2023_1_offset__end.Int;
	self.Float = __start.Float + my_app__dc_motor2023_1_offset__end.Float;
	self.Char = __start.Char + my_app__dc_motor2023_1_offset__end.Char;

	return 0;
}

