/*2024-03-18T11:53:50-01:00*/

/********************************************************************
 * dc_motor2023_1.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__DC_MOTOR2023_1_H
#define _MY_APP__DC_MOTOR2023_1_H


/********************** Variable declarations ***********************/

extern CB_Index dc_motor2023_1__num;

/********************** Function declarations ***********************/

extern int _my_app__dc_motor2023_1_init(void);
extern int my_app__dc_motor2023_1(void);

#endif /*_MY_APP__DC_MOTOR2023_1_H*/
