/*2024-03-18T09:05:27-01:00*/

/********************************************************************
 * dc_motor2023.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__DC_MOTOR2023_H
#define _MY_APP__DC_MOTOR2023_H


/********************** Variable declarations ***********************/

extern CB_Index dc_motor2023__num;

/********************** Function declarations ***********************/

extern int _my_app__dc_motor2023_init(void);
extern int my_app__dc_motor2023(void);

#endif /*_MY_APP__DC_MOTOR2023_H*/
