/*2024-03-18T18:00:00-01:00*/

/********************************************************************
 * tni_clock_1.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__TNI_CLOCK_1_H
#define _MY_APP__TNI_CLOCK_1_H


/********************** Variable declarations ***********************/

extern CB_Index tni_clock_1__num;
extern CB_Mem_Int *tni_clock_1_depth;
extern CB_Mem_Bool *tni_clock_1_B1;
extern CB_Mem_Bool *tni_clock_1_B2;
extern CB_Mem_Bool *tni_clock_1_B3;
extern CB_Mem_Bool *tni_clock_1_B4;

/********************** Function declarations ***********************/

extern int _my_app__tni_clock_1_init(void);
extern int my_app__tni_clock_1(void);

#endif /*_MY_APP__TNI_CLOCK_1_H*/
