/*2024-03-20T17:34:47-01:00*/

/********************************************************************
 * rien.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _ZOZO__RIEN_H
#define _ZOZO__RIEN_H


/********************** Variable declarations ***********************/

extern CB_Index rien__num;
extern CB_Mem_Bool *rien_s;
extern CB_Mem_Bool *rien_s2;

/********************** Function declarations ***********************/

extern int _zozo__rien_init(void);
extern int zozo__rien(void);

#endif /*_ZOZO__RIEN_H*/
