/*2024-03-18T18:01:40-01:00*/

/********************************************************************
 * tni_clock_2.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _MY_APP__TNI_CLOCK_2_H
#define _MY_APP__TNI_CLOCK_2_H


/********************** Variable declarations ***********************/

extern CB_Index tni_clock_2__num;
extern CB_Mem_Int *tni_clock_2_depth;
extern CB_Mem_Bool *tni_clock_2_B1;
extern CB_Mem_Bool *tni_clock_2_B2;
extern CB_Mem_Bool *tni_clock_2_B3;
extern CB_Mem_Bool *tni_clock_2_B4;

/********************** Function declarations ***********************/

extern int _my_app__tni_clock_2_init(void);
extern int my_app__tni_clock_2(void);

#endif /*_MY_APP__TNI_CLOCK_2_H*/
